Repository Romeo-Aryal/C-program-fest2022, pull requests merged in 2022-10, with the labels that each got.

#8 Create sushma33
  sushma33
Labels: hactoberfest, hactoberfest-accepted

#7 Create armstrong_number.c
  armstrong_number.c
Labels: hactoberfest, hactoberfest-accepted

#6 modified readme properly and added few programs
  Eligiblity.c
  README.md
  recursion.c
Labels: hactoberfest, hactoberfest-accepted

#13 added a C program guessing the number with comments. Its a fun game
  guess_the_number_game.c
Labels: hactoberfest, hactoberfest-accepted

#12 Create program.md
  program.md
Labels: hactoberfest, hactoberfest-accepted

#11 added code of priority queue using java
  Heap.java
Labels: hactoberfest, hactoberfest-accepted

#10 Graph basics
  Graphs/bfs.cpp
  Graphs/dfs.cpp
  Graphs/dijkstras.cpp
  Graphs/topologicalSort.cpp
Labels: hactoberfest, hactoberfest-accepted

#16 Added C program that removes duplicates from an array
  removeDuplicates.c
Labels: hactoberfest, hactoberfest-accepted

#15 Greatesr_Common_Divisor.c
  Greatesr_Common_Divisor.c
Labels: hactoberfest, hactoberfest-accepted

#14 Fibonacci_Recursion.c
  fibonacci_Recursion.c
Labels: hactoberfest, hactoberfest-accepted

#19 Added a c program
  C program to dispaly squares of number from  0 to 14.c
Labels: hactoberfest, hactoberfest-accepted

#18 Hacktoberfest-2022
  reverse_string.c
  stringComapre.c
Labels: hactoberfest, hactoberfest-accepted

#17 Create c++.md
  c++.md
Labels: hactoberfest, hactoberfest-accepted

#23 Create linked list
  linked_list.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#22 Add files via upload
  alphabet.c
Labels: hacktoberfest, hacktoberfest-accepted

#21 factorial_subhagata
  factorial.c
Labels: hacktoberfest, hacktoberfest-accepted

#26 Added python code as per c code
  1_Hello_program.py
  2.Playing_with_characters.py
  3.sum and diff of two numbers.py
  atmstrong_number.py
  factorial.py
  finbonacci_series.py
Labels: hacktoberfest, hacktoberfest-accepted

#28 sort N numbers in ascending order
  Bubble Short.c
Labels: hacktoberfest, hacktoberfest-accepted

#31 Create Palindrome_Problem.c
  Palindrome_Problem.c
Labels: hacktoberfest, hacktoberfest-accepted

#35 reverse a string by swapping in c
  reverse string by swapping.c
Labels: hacktoberfest, hacktoberfest-accepted

#34 added some c programs
  palindrome.c
  pyramid.c
  stringSorting.c
Labels: hacktoberfest, hacktoberfest-accepted

#33 A menu based program
  A menu based program.c
Labels: hacktoberfest, hacktoberfest-accepted

#32 stack.cpp
  stack.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#36 added some c program
  C-program-fest2022/1.Hello_program.c
  C-program-fest2022/1_Hello_program.py
  C-program-fest2022/2.Playing_with_characters.c
  C-program-fest2022/2.Playing_with_characters.py
  C-program-fest2022/3.sum and diff of two numbers.c
  C-program-fest2022/3.sum and diff of two numbers.py
  C-program-fest2022/C program to dispaly squares of number from  0 to 14.c
  C-program-fest2022/CircularLinkedList.c
  C-program-fest2022/Count_Sort.c
  C-program-fest2022/Eligiblity.c
  C-program-fest2022/Graphs/bfs.cpp
  C-program-fest2022/Graphs/dfs.cpp
  C-program-fest2022/Graphs/dijkstras.cpp
  C-program-fest2022/Graphs/topologicalSort.cpp
  C-program-fest2022/Greatesr_Common_Divisor.c
  C-program-fest2022/Heap.java
  C-program-fest2022/README.md
  C-program-fest2022/alphabet.c
  C-program-fest2022/armstrong.c
  C-program-fest2022/armstrong_number.c
  C-program-fest2022/atmstrong_number.py
  C-program-fest2022/bmicalc.c
  C-program-fest2022/c++.md
  C-program-fest2022/chess game by sijan.c
  C-program-fest2022/creating a linked list.c
  C-program-fest2022/factorial.c
  C-program-fest2022/factorial.py
  C-program-fest2022/fibonacci series
  C-program-fest2022/fibonacci_Recursion.c
  C-program-fest2022/finbonacci_series.py
  C-program-fest2022/guess_the_number_game.c
  C-program-fest2022/leap year.c
  C-program-fest2022/linked_list.cpp
  C-program-fest2022/namearranging.c
  C-program-fest2022/palindrome number.c
  C-program-fest2022/program-2.c
  C-program-fest2022/program.md
  C-program-fest2022/program1.c
  C-program-fest2022/program3.c
  C-program-fest2022/program4.c
  C-program-fest2022/program5.c
  C-program-fest2022/programBitcoin.c
  C-program-fest2022/recursion.c
  C-program-fest2022/removeDuplicates.c
  C-program-fest2022/reverse_string.c
  C-program-fest2022/stringComapre.c
  C-program-fest2022/studentdata.cpp
  C-program-fest2022/sushma33
  C-program-fest2022/swapWithoutThirdVariable.c
Labels: hacktoberfest, hacktoberfest-accepted

#40 Added marksheet program with c .
  C-program-fest2022/A menu based program.c
  C-program-fest2022/Bubble Short.c
  C-program-fest2022/Palindrome_Problem.c
  C-program-fest2022/Tip calculator/index.html
  C-program-fest2022/Tip calculator/script.js
  C-program-fest2022/Tip calculator/style.css
  C-program-fest2022/marksheet.c
  C-program-fest2022/member Function.cpp
  C-program-fest2022/palindrome.c
  C-program-fest2022/pyramid.c
  C-program-fest2022/reverse string by swapping.c
  C-program-fest2022/stack.cpp
  C-program-fest2022/stringSorting.c
Labels: hacktoberfest, hacktoberfest-accepted

#42 Create matrix_finder.c
  matrix_finder.c
Labels: hacktoberfest, hacktoberfest-accepted

#41 fibonacci series code
  fibonacci_series.c
Labels: hacktoberfest, hacktoberfest-accepted

#46 PointerToPointer.c
  PointerToPointer.c
Labels: hacktoberfest, hacktoberfest-accepted

#45 Added Sparse_Matrix Implementation and Updated Contributors List in Readme.md
  C-program-fest2022/README.md
  C-program-fest2022/SparseMatrix.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#44 Added a rajiv program
  rajiv.c
Labels: hacktoberfest, hacktoberfest-accepted

#43 I've added program to sort elements ( Merge Sort).
  binsearch.c
  mergesort.c
Labels: hacktoberfest, hacktoberfest-accepted

#50 Added reverse stack implementation
  reverse_stack.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#47 Create Insertion_Sort
  Insertion_Sort
Labels: hacktoberfest, hacktoberfest-accepted

#55 Create Recursive Binary Search.c
  Recursive Binary Search.c
Labels: hacktoberfest, hacktoberfest-accepted

#54 A NEW INTRSTING GAME IS ADDED
  scissor_paper_rock.c
Labels: hacktoberfest, hacktoberfest-accepted

#52 alogorithm for calculating factorial of Big Int
  factorial_off_big_number.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#53 infix expresion to postfix conversion
  infix_to_postfix.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#51 File encryption Program by 047pegasus commit
  C-program-fest2022/Encrypt.cpp
  C-program-fest2022/RandomArrayGenerator.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#57 Sum of even numbers
  sudikshya.exe
Labels: hacktoberfest, hacktoberfest-accepted

#58 Anagram
  anagram.c
Labels: hacktoberfest, hacktoberfest-accepted

#59 Added basic operation on BST.
  basicOperationOnBST.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#61 Mid point of a linked list
  reverse_and_midpoint_linkedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#65 added matrix determinant calculation program in cpp
  C-program-fest2022/matrix_determinant.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#64 Basic calculator using Switch statements.
  calculator.c
  leap year.c
Labels: hacktoberfest, hacktoberfest-accepted

#63 Maximum Clique Graph
  Graphs/maximum_clique.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#67 Number Triangle
  assemblysum.c
  numtriangle.c
Labels: hacktoberfest, hacktoberfest-accepted

#62 Added balance paranthesis standard stack problem
  balanceParanthesis.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#60 Added a sliding window standard problem.
  subArray.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#49 Added linked list all the basic operations
  basicOperation.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#48 Added disjoinnt set union algorithm.
  disjoint_set_union.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#83 Add files via upload
  infixtoprefixandpostfix.c
Labels: hacktoberfest, hacktoberfest-accepted

#82 To print transpose of matrix
  Merging array.c
  swap.c
  transpose.c
Labels: hacktoberfest, hacktoberfest-accepted

#80 create stack without using structure
  stack_no_struct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#77 Employee DB Management System commit by 047pegasus
  C-program-fest2022/EmployeeDB.cpp
  C-program-fest2022/WordGuessingGame.py
Labels: hacktoberfest, hacktoberfest-accepted

#75 Added Half pyramid in c
  Half_pyramid.c
Labels: hacktoberfest, hacktoberfest-accepted

#74 Created Least_Common_Multiple.c
  Least_Common_Multiple.c
Labels: hacktoberfest, hacktoberfest-accepted

#73 Created balanced_Parentheses.c
  balanced_parentheses.c
Labels: hacktoberfest, hacktoberfest-accepted

#72 Add files via upload
  bank management system.c.txt
Labels: hacktoberfest, hacktoberfest-accepted

#71 addcprogram
  circularLL.c
Labels: hacktoberfest, hacktoberfest-accepted

#69 Vowel or Not
  vowel.c
Labels: hacktoberfest, hacktoberfest-accepted

#68 add problem statement: check if is pangram
  check_Sentence.py
Labels: hacktoberfest, hacktoberfest-accepted

#87 Library management system C
  Book.dat
  LibraryManagementSystem.c
Labels: hacktoberfest, hacktoberfest-accepted

#86 Half pyramid pattern in C++
  C-program-fest2022/half_pyramid.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#84 Created Tic Tac Toe.py(Hacktoberfest 2k22)
  Tic Tac Toe.py
Labels: hacktoberfest, hacktoberfest-accepted

#97 Created Count_Occurence_of _given_character.c
  Count_Occurence_of _given_character.c
Labels: hacktoberfest, hacktoberfest-accepted

#99 Added priority cpu scheduling
  priority.c
  roundrobin.c
Labels: hacktoberfest, hacktoberfest-accepted

#104 Create Counting-sort
  Counting-sort
Labels: hacktoberfest, hacktoberfest-accepted

#103 Create Bucket-sort
  Bucket-sort
Labels: hacktoberfest, hacktoberfest-accepted

#101 Create Comb-sort
  Comb-sort
Labels: hacktoberfest, hacktoberfest-accepted

#95 Maze Runner
  mazerunner.py
Labels: hacktoberfest, hacktoberfest-accepted

#94 Create Merge_Sort.c
  C-program-fest2022/Merge_Sort.c
Labels: hacktoberfest, hacktoberfest-accepted

#93 Added a C program that prints all the substrings of a given string
  C-program-fest2022/allSubstrings.c
Labels: hacktoberfest, hacktoberfest-accepted

#92 Create Digital_Clock.c
  Digital_Clock.c
Labels: hacktoberfest, hacktoberfest-accepted

#90 Create Double_Linked_List.c
  C-program-fest2022/Double_Linked_List.c
Labels: hacktoberfest, hacktoberfest-accepted

#89 Add files via upload
  Cartesianproduct.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#88 Add files via upload
  Countdigitsvowelsinstring.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#108 Add files via upload
  Circle.c
Labels: hacktoberfest, hacktoberfest-accepted

#106 Create factorial_using_recursion.c
  factorial_using_recursion.c
Labels: hacktoberfest, hacktoberfest-accepted

#107 Check if a graph is strongly/weakly connected
  Graphs/graphstrongweak.c
Labels: hacktoberfest, hacktoberfest-accepted

#109 Complex Number
  ComplexNumber.c
Labels: hacktoberfest, hacktoberfest-accepted

#110 Infix_to_Prefix&Postfix_and_Postfix_evaluation
  C-program-fest2022/Infix_to_Prefix&Postfix_and_Postfix_evaluation.c
Labels: hacktoberfest, hacktoberfest-accepted

#115 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#111 Add files via upload
  linearsearch.c
Labels: hacktoberfest, hacktoberfest-accepted

#112 Create widthHeight.java
  widthHeight.java
Labels: hacktoberfest, hacktoberfest-accepted

#116 Added C program that checks whether the given character is alphabet or not
  isAlphabetOrNot.c
Labels: hacktoberfest, hacktoberfest-accepted

#117 Create quick sort
  quick sort
Labels: hacktoberfest, hacktoberfest-accepted

#118 Added code for selection sort
  selectionsort.c
Labels: hacktoberfest, hacktoberfest-accepted

#119 Added a code for AVL Tree in C
  C-program-fest2022/AVL_Tree.c
Labels: hacktoberfest, hacktoberfest-accepted

#113 Create Valid_sudoku.py
  Valid_sudoku.py
Labels: hacktoberfest, hacktoberfest-accepted

#114 Create Collatz_Sequence.py
  Collatz_Sequence.py
Labels: hacktoberfest, hacktoberfest-accepted

#120 Create generate-random-color.cpp
  cool stuffs in c/generate-random-color.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#121 Added a C program "rat in maze" which is an example of Backtracking
  C-program-fest2022/ratInMaze.c
Labels: hacktoberfest, hacktoberfest-accepted

#122 Bubble sort
  Bubblesort.c
Labels: hacktoberfest, hacktoberfest-accepted

#123 Optional pattern
  cool stuffs in c/Optional_pattern.c
  cool stuffs in c/quiz-game.exe
Labels: hacktoberfest, hacktoberfest-accepted

#124 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#125 String and Vector-Pair Programs
  stringandRecursion/climbingstrais.cpp
  stringandRecursion/fibonacci.cpp
  stringandRecursion/octo.cpp
  stringandRecursion/pair_1.cpp
  stringandRecursion/stingfind.cpp
  stringandRecursion/string_1.cpp
  stringandRecursion/string_accur-num.cpp
  stringandRecursion/string_casechange.cpp
  stringandRecursion/string_maxnum.cpp
  stringandRecursion/stringadd.cpp
  stringandRecursion/stringcompare.cpp
  stringandRecursion/stringerase.cpp
  stringandRecursion/stringinsert.cpp
  stringandRecursion/stringsort.cpp
  stringandRecursion/stringsubstring.cpp
  stringandRecursion/stringto_int.cpp
  stringandRecursion/vector_1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#127 Added Weighted Directed graph
  C-program-fest2022/Graphs/Graphs in C/weightedDirectedGraph.c
Labels: hacktoberfest, hacktoberfest-accepted

#128 added code for matrix multiplication
  C-program-fest2022/matrixmultiplication.c
Labels: hacktoberfest, hacktoberfest-accepted

#129 Added Prims_MST.c
  Graphs/Prims_MST.c
Labels: hacktoberfest, hacktoberfest-accepted

#131 add code of factorial
  C-program-fest2022/factorial.c.eml
Labels: hacktoberfest, hacktoberfest-accepted

#132 Added a_star.cpp
  Graphs/a_star.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#133 Create beautifulMatrix.cpp
  beautifulMatrix.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#134 C | Total of two indices values equal a target
  Total of two indices values equal a target.c
Labels: hacktoberfest, hacktoberfest-accepted

#147 Decimal to Binary Conversion
  decimal_to_binary.c
Labels: hacktoberfest, hacktoberfest-accepted

#145 Create insertion_linkedlist.c
  insertion_linkedlist.c
Labels: hacktoberfest, hacktoberfest-accepted

#146 Add a program to find LCA in a tree
  String_Hashing.cpp
  lowest_common_ancestor.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#144 Shell Sort implementation using Java
  Shell_Sort
Labels: hacktoberfest, hacktoberfest-accepted

#143 Create Egg_Catcher_Game.py
  Egg_Catcher_Game.py
Labels: hacktoberfest, hacktoberfest-accepted

#142 Binary Tree Traversal Techniques
  Binary Tree Traversal.cpp
  Stack using Linked List.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#141 Stack using Linkedlist
  Stack using Linked List.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#135 c program to check wheather the number is palindrome or not | Issue #127 solved
  Check wheather number is palindrome.c
Labels: hacktoberfest, hacktoberfest-accepted

#136 Create merge sort in python.py
  merge sort in python.py
Labels: hacktoberfest, hacktoberfest-accepted

#137 added fibonacci sequence code
  fibonacci.js
Labels: hacktoberfest, hacktoberfest-accepted

#138 implementation of merge sort in c
  mergeSort-implementation.c
Labels: hacktoberfest, hacktoberfest-accepted

#139 added an algorithm
  radix_sort.c
Labels: hacktoberfest, hacktoberfest-accepted

#140 Climbing stairs
  Climbing stairs.java
Labels: hacktoberfest, hacktoberfest-accepted

#155 added program for convert roman number to integer number
  roman_to_integer.c
Labels: hacktoberfest, hacktoberfest-accepted

#154 Created a Password Generator using C.
  C-program-fest2022/PasswordGenerator.c
Labels: hacktoberfest, hacktoberfest-accepted

#153 Add a program to find longest increasing subsequence
  Check_Substring_Palindrome_in_logn_time.cpp
  disjoint_set_union.cpp
  longest_increasing_subsequence.cpp
  power_of_a_number_using_binary_exponentiation.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#149 Add a program to check whether a substring is a palindrome or not in logn time complexity.
  Check_Substring_Palindrome_in_logn_time.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#150 Implementation of Banking system using C++
  Banking_system.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#148 check
  palindromes
  palindromes.c
Labels: hacktoberfest, hacktoberfest-accepted

#157 Create SimpleInterestCalculator
  C-program-fest2022/SimpleInterestCalculator
Labels: hacktoberfest

#156 Added Stack and Queue Programs in C
  QUEUES in C/circular.c
  QUEUES in C/practice.c
  QUEUES in C/queueUstack.c
  QUEUES in C/queue__LL.c
  STACK in C/Brackets.c
  STACK in C/InfixTOpostfix.c
  STACK in C/lab.c
  STACK in C/palindrome.c
  STACK in C/paranthesis.c
  STACK in C/push.c
  STACK in C/stack.c
  STACK in C/stackUlinkedlist.c
Labels: hacktoberfest

#160 Please merge my PR
  C-program-fest2022/Find_the_longest_path_in_a_matrix_with_given_constraints.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#159 currency converter
  currency converter
Labels: hacktoberfest, hacktoberfest-accepted

#158 C Program to Check Whether a Number is Palindrome or Not.c
  C Program to Check Whether a Number is Palindrome or Not.c
Labels: hacktoberfest, hacktoberfest-accepted
